-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.area
(
    area_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    nombre character varying(120) COLLATE pg_catalog."default" NOT NULL,
    descripcion character varying(500) COLLATE pg_catalog."default",
    CONSTRAINT area_pkey PRIMARY KEY (area_id)
);

CREATE TABLE IF NOT EXISTS public.areas_cliente
(
    areas_cliente_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    CONSTRAINT areas_cliente_pkey PRIMARY KEY (areas_cliente_id)
);

CREATE TABLE IF NOT EXISTS public.auth_user
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    password character varying(128) COLLATE pg_catalog."default" NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) COLLATE pg_catalog."default" NOT NULL,
    first_name character varying(150) COLLATE pg_catalog."default" NOT NULL,
    last_name character varying(150) COLLATE pg_catalog."default" NOT NULL,
    email character varying(254) COLLATE pg_catalog."default" NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL,
    CONSTRAINT auth_user_pkey PRIMARY KEY (id),
    CONSTRAINT auth_user_username_key UNIQUE (username)
);

CREATE TABLE IF NOT EXISTS public.ciudad
(
    ciudad_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    nombre character varying(120) COLLATE pg_catalog."default",
    departamento_id integer,
    CONSTRAINT ciudad_pkey PRIMARY KEY (ciudad_id)
);

CREATE TABLE IF NOT EXISTS public.cliente
(
    cliente_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    nit_cliente character varying(50) COLLATE pg_catalog."default" NOT NULL,
    nombre character varying(120) COLLATE pg_catalog."default" NOT NULL,
    email character varying(120) COLLATE pg_catalog."default",
    direccion character varying(250) COLLATE pg_catalog."default",
    telefono character varying(100) COLLATE pg_catalog."default",
    nombre_contacto character varying(120) COLLATE pg_catalog."default",
    ciudad_id integer NOT NULL,
    tipo_cliente_id integer NOT NULL,
    activo boolean NOT NULL,
    coordinador_id bigint,
    sector character varying(50) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT cliente_pkey PRIMARY KEY (cliente_id),
    CONSTRAINT cliente_nit_cliente_key UNIQUE (nit_cliente)
);

CREATE TABLE IF NOT EXISTS public.clientes_coordinador
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    user_id integer NOT NULL,
    CONSTRAINT clientes_coordinador_pkey PRIMARY KEY (id),
    CONSTRAINT clientes_coordinador_user_id_key UNIQUE (user_id)
);

CREATE TABLE IF NOT EXISTS public.clientes_datosmensajero
(
    datos_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    CONSTRAINT clientes_datosmensajero_pkey PRIMARY KEY (datos_id)
);

CREATE TABLE IF NOT EXISTS public.clientes_mensajeroaquitoy
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    user_id integer NOT NULL,
    activo boolean NOT NULL,
    fecha_entrada date,
    fecha_salida date,
    salario bigint,
    telefono character varying(15) COLLATE pg_catalog."default",
    ciudad_operacion_id integer,
    "token_Firebase" character varying(500) COLLATE pg_catalog."default",
    url_foto character varying(1000) COLLATE pg_catalog."default",
    CONSTRAINT clientes_mensajeroaquitoy_pkey PRIMARY KEY (id),
    CONSTRAINT clientes_mensajeroaquitoy_user_id_key UNIQUE (user_id)
);

CREATE TABLE IF NOT EXISTS public.clientes_mensajeroaquitoy_clientes
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    mensajeroaquitoy_id bigint NOT NULL,
    cliente_id integer NOT NULL,
    CONSTRAINT clientes_mensajeroaquitoy_clientes_pkey PRIMARY KEY (id),
    CONSTRAINT clientes_mensajeroaquito_mensajeroaquitoy_id_clie_0d4071ec_uniq UNIQUE (mensajeroaquitoy_id, cliente_id)
);

CREATE TABLE IF NOT EXISTS public.clientes_usuarioaquitoy
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    ciudad_id integer NOT NULL,
    user_id integer NOT NULL,
    telefono character varying(15) COLLATE pg_catalog."default" NOT NULL,
    area_id integer NOT NULL,
    cliente_id integer NOT NULL,
    sede_id integer NOT NULL,
    "token_Firebase" character varying(500) COLLATE pg_catalog."default",
    lider boolean NOT NULL,
    CONSTRAINT clientes_usuarioaquitoy_pkey PRIMARY KEY (id),
    CONSTRAINT clientes_usuarioaquitoy_user_id_key UNIQUE (user_id)
);

CREATE TABLE IF NOT EXISTS public.departamento
(
    departamento_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    nombre character varying(120) COLLATE pg_catalog."default",
    CONSTRAINT departamento_pkey PRIMARY KEY (departamento_id)
);

CREATE TABLE IF NOT EXISTS public.mensajeria_destinoservicio
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    direccion character varying(500) COLLATE pg_catalog."default" NOT NULL,
    cliente_id integer NOT NULL,
    ciudad_id integer,
    CONSTRAINT mensajeria_destinoservicio_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.mensajeria_documentoasociado
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    numero character varying(50) COLLATE pg_catalog."default" NOT NULL,
    servicio_id integer NOT NULL,
    CONSTRAINT mensajeria_documentoasociado_pkey PRIMARY KEY (id),
    CONSTRAINT mensajeria_documentoasociado_numero_key UNIQUE (numero)
);

CREATE TABLE IF NOT EXISTS public.mensajeria_estado
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    nombre character varying(75) COLLATE pg_catalog."default" NOT NULL,
    descripcion character varying(500) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT mensajeria_estado_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.mensajeria_estadosservicio
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    fecha date NOT NULL,
    hora time without time zone NOT NULL,
    foto character varying(500) COLLATE pg_catalog."default",
    observaciones character varying(500) COLLATE pg_catalog."default",
    estado_id integer NOT NULL,
    servicio_id integer NOT NULL,
    es_prueba boolean NOT NULL,
    foto_binary bytea,
    CONSTRAINT mensajeria_estadosservicio_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.mensajeria_novedadesservicio
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    fecha_novedad timestamp with time zone,
    tipo_novedad_id integer NOT NULL,
    descripcion character varying(700) COLLATE pg_catalog."default",
    servicio_id integer NOT NULL,
    es_prueba boolean NOT NULL,
    mensajero_id bigint NOT NULL,
    CONSTRAINT mensajeria_novedadesservicio_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.mensajeria_origenservicio
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    direccion character varying(500) COLLATE pg_catalog."default" NOT NULL,
    cliente_id integer NOT NULL,
    ciudad_id integer,
    CONSTRAINT mensajeria_origenservicio_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.mensajeria_servicio
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    descripcion character varying(700) COLLATE pg_catalog."default" NOT NULL,
    nombre_solicitante character varying(100) COLLATE pg_catalog."default" NOT NULL,
    fecha_solicitud date NOT NULL,
    hora_solicitud time without time zone NOT NULL,
    fecha_deseada date NOT NULL,
    hora_deseada time without time zone,
    nombre_recibe character varying(100) COLLATE pg_catalog."default" NOT NULL,
    telefono_recibe character varying(30) COLLATE pg_catalog."default",
    descripcion_pago character varying(500) COLLATE pg_catalog."default",
    ida_y_regreso boolean NOT NULL,
    activo boolean NOT NULL,
    novedades character varying(500) COLLATE pg_catalog."default",
    cliente_id integer NOT NULL,
    destino_id integer NOT NULL,
    mensajero_id bigint,
    origen_id integer NOT NULL,
    tipo_pago_id integer NOT NULL,
    tipo_servicio_id integer,
    tipo_vehiculo_id integer NOT NULL,
    usuario_id bigint NOT NULL,
    prioridad character varying(50) COLLATE pg_catalog."default",
    ciudad_destino_id integer NOT NULL,
    ciudad_origen_id integer NOT NULL,
    hora_visto_por_mensajero time without time zone,
    visto_por_mensajero character varying(250) COLLATE pg_catalog."default",
    descripcion_multiples_origenes character varying(700) COLLATE pg_catalog."default",
    mensajero2_id bigint,
    mensajero3_id bigint,
    multiples_origenes boolean NOT NULL,
    asignar_mensajero boolean NOT NULL,
    es_prueba boolean NOT NULL,
    descripcion_cancelado character varying(500) COLLATE pg_catalog."default",
    CONSTRAINT mensajeria_servicio_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.mensajeria_tiponovedad
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    nombre character varying(30) COLLATE pg_catalog."default",
    CONSTRAINT mensajeria_tiponovedad_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.mensajeria_tipopago
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    nombre character varying(75) COLLATE pg_catalog."default" NOT NULL,
    descripcion character varying(500) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT mensajeria_tipopago_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.mensajeria_tiposervicio
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    nombre character varying(75) COLLATE pg_catalog."default" NOT NULL,
    descripcion character varying(500) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT mensajeria_tiposervicio_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.mensajeria_tipovehiculo
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    nombre character varying(75) COLLATE pg_catalog."default" NOT NULL,
    descripcion character varying(500) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT mensajeria_tipovehiculo_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.sede
(
    sede_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    nombre character varying(120) COLLATE pg_catalog."default" NOT NULL,
    direccion character varying(250) COLLATE pg_catalog."default",
    telefono character varying(100) COLLATE pg_catalog."default",
    nombre_contacto character varying(120) COLLATE pg_catalog."default",
    ciudad_id integer NOT NULL,
    cliente_id integer NOT NULL,
    CONSTRAINT sede_pkey PRIMARY KEY (sede_id)
);

CREATE TABLE IF NOT EXISTS public.tipo_cliente
(
    tipo_cliente_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    nombre character varying(120) COLLATE pg_catalog."default",
    descripcion character varying(250) COLLATE pg_catalog."default",
    CONSTRAINT tipo_cliente_pkey PRIMARY KEY (tipo_cliente_id)
);

ALTER TABLE IF EXISTS public.ciudad
    ADD CONSTRAINT ciudad_departamento_id_a4e11c8e_fk_departamento_departamento_id FOREIGN KEY (departamento_id)
    REFERENCES public.departamento (departamento_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS ciudad_departamento_id_a4e11c8e
    ON public.ciudad(departamento_id);


ALTER TABLE IF EXISTS public.cliente
    ADD CONSTRAINT cliente_ciudad_id_3cb4d789_fk_ciudad_ciudad_id FOREIGN KEY (ciudad_id)
    REFERENCES public.ciudad (ciudad_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS cliente_ciudad_id_3cb4d789
    ON public.cliente(ciudad_id);


ALTER TABLE IF EXISTS public.cliente
    ADD CONSTRAINT cliente_coordinador_id_c383b6d1_fk_clientes_coordinador_id FOREIGN KEY (coordinador_id)
    REFERENCES public.clientes_coordinador (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS cliente_coordinador_id_c383b6d1
    ON public.cliente(coordinador_id);


ALTER TABLE IF EXISTS public.cliente
    ADD CONSTRAINT cliente_tipo_cliente_id_3589fa04_fk_tipo_clie FOREIGN KEY (tipo_cliente_id)
    REFERENCES public.tipo_cliente (tipo_cliente_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS cliente_tipo_cliente_id_3589fa04
    ON public.cliente(tipo_cliente_id);


ALTER TABLE IF EXISTS public.clientes_coordinador
    ADD CONSTRAINT clientes_coordinador_user_id_d47fc754_fk_auth_user_id FOREIGN KEY (user_id)
    REFERENCES public.auth_user (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS clientes_coordinador_user_id_key
    ON public.clientes_coordinador(user_id);


ALTER TABLE IF EXISTS public.clientes_mensajeroaquitoy
    ADD CONSTRAINT clientes_mensajeroaq_ciudad_operacion_id_c722e4ee_fk_ciudad_ci FOREIGN KEY (ciudad_operacion_id)
    REFERENCES public.ciudad (ciudad_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS clientes_mensajeroaquitoy_ciudad_operacion_id_c722e4ee
    ON public.clientes_mensajeroaquitoy(ciudad_operacion_id);


ALTER TABLE IF EXISTS public.clientes_mensajeroaquitoy
    ADD CONSTRAINT clientes_mensajeroaquitoy_user_id_15f7926d_fk_auth_user_id FOREIGN KEY (user_id)
    REFERENCES public.auth_user (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS clientes_mensajeroaquitoy_user_id_key
    ON public.clientes_mensajeroaquitoy(user_id);


ALTER TABLE IF EXISTS public.clientes_mensajeroaquitoy_clientes
    ADD CONSTRAINT clientes_mensajeroaq_cliente_id_ef01b0c6_fk_cliente_c FOREIGN KEY (cliente_id)
    REFERENCES public.cliente (cliente_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS clientes_mensajeroaquitoy_clientes_cliente_id_ef01b0c6
    ON public.clientes_mensajeroaquitoy_clientes(cliente_id);


ALTER TABLE IF EXISTS public.clientes_mensajeroaquitoy_clientes
    ADD CONSTRAINT clientes_mensajeroaq_mensajeroaquitoy_id_871b7c77_fk_clientes_ FOREIGN KEY (mensajeroaquitoy_id)
    REFERENCES public.clientes_mensajeroaquitoy (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS clientes_mensajeroaquitoy_clientes_mensajeroaquitoy_id_871b7c77
    ON public.clientes_mensajeroaquitoy_clientes(mensajeroaquitoy_id);


ALTER TABLE IF EXISTS public.clientes_usuarioaquitoy
    ADD CONSTRAINT clientes_usuarioaqui_cliente_id_0be12407_fk_cliente_c FOREIGN KEY (cliente_id)
    REFERENCES public.cliente (cliente_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS clientes_usuarioaquitoy_cliente_id_0be12407
    ON public.clientes_usuarioaquitoy(cliente_id);


ALTER TABLE IF EXISTS public.clientes_usuarioaquitoy
    ADD CONSTRAINT clientes_usuarioaquitoy_area_id_f36410ef_fk_area_area_id FOREIGN KEY (area_id)
    REFERENCES public.area (area_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS clientes_usuarioaquitoy_area_id_f36410ef
    ON public.clientes_usuarioaquitoy(area_id);


ALTER TABLE IF EXISTS public.clientes_usuarioaquitoy
    ADD CONSTRAINT clientes_usuarioaquitoy_ciudad_id_d0916e9a_fk_ciudad_ciudad_id FOREIGN KEY (ciudad_id)
    REFERENCES public.ciudad (ciudad_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS clientes_usuarioaquitoy_ciudad_id_d0916e9a
    ON public.clientes_usuarioaquitoy(ciudad_id);


ALTER TABLE IF EXISTS public.clientes_usuarioaquitoy
    ADD CONSTRAINT clientes_usuarioaquitoy_sede_id_dff4d455_fk_sede_sede_id FOREIGN KEY (sede_id)
    REFERENCES public.sede (sede_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS clientes_usuarioaquitoy_sede_id_dff4d455
    ON public.clientes_usuarioaquitoy(sede_id);


ALTER TABLE IF EXISTS public.clientes_usuarioaquitoy
    ADD CONSTRAINT clientes_usuarioaquitoy_user_id_7cd70874_fk_auth_user_id FOREIGN KEY (user_id)
    REFERENCES public.auth_user (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS clientes_usuarioaquitoy_user_id_key
    ON public.clientes_usuarioaquitoy(user_id);


ALTER TABLE IF EXISTS public.mensajeria_destinoservicio
    ADD CONSTRAINT mensajeria_destinose_ciudad_id_559aa3e0_fk_ciudad_ci FOREIGN KEY (ciudad_id)
    REFERENCES public.ciudad (ciudad_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS mensajeria_destinoservicio_ciudad_id_559aa3e0
    ON public.mensajeria_destinoservicio(ciudad_id);


ALTER TABLE IF EXISTS public.mensajeria_destinoservicio
    ADD CONSTRAINT mensajeria_destinose_cliente_id_aa09a658_fk_cliente_c FOREIGN KEY (cliente_id)
    REFERENCES public.cliente (cliente_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS mensajeria_destinoservicio_cliente_id_aa09a658
    ON public.mensajeria_destinoservicio(cliente_id);


ALTER TABLE IF EXISTS public.mensajeria_documentoasociado
    ADD CONSTRAINT mensajeria_documento_servicio_id_7b1d6698_fk_mensajeri FOREIGN KEY (servicio_id)
    REFERENCES public.mensajeria_servicio (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS mensajeria_documentoasociado_servicio_id_7b1d6698
    ON public.mensajeria_documentoasociado(servicio_id);


ALTER TABLE IF EXISTS public.mensajeria_estadosservicio
    ADD CONSTRAINT mensajeria_estadosse_estado_id_935615a0_fk_mensajeri FOREIGN KEY (estado_id)
    REFERENCES public.mensajeria_estado (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS mensajeria_estadosservicio_estado_id_935615a0
    ON public.mensajeria_estadosservicio(estado_id);


ALTER TABLE IF EXISTS public.mensajeria_estadosservicio
    ADD CONSTRAINT mensajeria_estadosse_servicio_id_05878b7b_fk_mensajeri FOREIGN KEY (servicio_id)
    REFERENCES public.mensajeria_servicio (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS mensajeria_estadosservicio_servicio_id_05878b7b
    ON public.mensajeria_estadosservicio(servicio_id);


ALTER TABLE IF EXISTS public.mensajeria_novedadesservicio
    ADD CONSTRAINT mensajeria_novedades_mensajero_id_66745990_fk_clientes_ FOREIGN KEY (mensajero_id)
    REFERENCES public.clientes_mensajeroaquitoy (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS mensajeria_novedadesservicio_mensajero_id_66745990
    ON public.mensajeria_novedadesservicio(mensajero_id);


ALTER TABLE IF EXISTS public.mensajeria_novedadesservicio
    ADD CONSTRAINT mensajeria_novedades_servicio_id_c18d535b_fk_mensajeri FOREIGN KEY (servicio_id)
    REFERENCES public.mensajeria_servicio (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS mensajeria_novedadesservicio_servicio_id_c18d535b
    ON public.mensajeria_novedadesservicio(servicio_id);


ALTER TABLE IF EXISTS public.mensajeria_novedadesservicio
    ADD CONSTRAINT mensajeria_novedades_tipo_novedad_id_879b09eb_fk_mensajeri FOREIGN KEY (tipo_novedad_id)
    REFERENCES public.mensajeria_tiponovedad (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS mensajeria_novedadesservicio_tipo_novedad_id_879b09eb
    ON public.mensajeria_novedadesservicio(tipo_novedad_id);


ALTER TABLE IF EXISTS public.mensajeria_origenservicio
    ADD CONSTRAINT mensajeria_origenser_ciudad_id_dfca7e93_fk_ciudad_ci FOREIGN KEY (ciudad_id)
    REFERENCES public.ciudad (ciudad_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS mensajeria_origenservicio_ciudad_id_dfca7e93
    ON public.mensajeria_origenservicio(ciudad_id);


ALTER TABLE IF EXISTS public.mensajeria_origenservicio
    ADD CONSTRAINT mensajeria_origenser_cliente_id_2e67e10a_fk_cliente_c FOREIGN KEY (cliente_id)
    REFERENCES public.cliente (cliente_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS mensajeria_origenservicio_cliente_id_2e67e10a
    ON public.mensajeria_origenservicio(cliente_id);


ALTER TABLE IF EXISTS public.mensajeria_servicio
    ADD CONSTRAINT mensajeria_servicio_ciudad_destino_id_c8bda500_fk_ciudad_ci FOREIGN KEY (ciudad_destino_id)
    REFERENCES public.ciudad (ciudad_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS mensajeria_servicio_ciudad_destino_id_c8bda500
    ON public.mensajeria_servicio(ciudad_destino_id);


ALTER TABLE IF EXISTS public.mensajeria_servicio
    ADD CONSTRAINT mensajeria_servicio_ciudad_origen_id_5d0db427_fk_ciudad_ci FOREIGN KEY (ciudad_origen_id)
    REFERENCES public.ciudad (ciudad_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS mensajeria_servicio_ciudad_origen_id_5d0db427
    ON public.mensajeria_servicio(ciudad_origen_id);


ALTER TABLE IF EXISTS public.mensajeria_servicio
    ADD CONSTRAINT mensajeria_servicio_cliente_id_501478ef_fk_cliente_cliente_id FOREIGN KEY (cliente_id)
    REFERENCES public.cliente (cliente_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS mensajeria_servicio_cliente_id_501478ef
    ON public.mensajeria_servicio(cliente_id);


ALTER TABLE IF EXISTS public.mensajeria_servicio
    ADD CONSTRAINT mensajeria_servicio_destino_id_e2f1d1b8_fk_mensajeri FOREIGN KEY (destino_id)
    REFERENCES public.mensajeria_destinoservicio (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS mensajeria_servicio_destino_id_e2f1d1b8
    ON public.mensajeria_servicio(destino_id);


ALTER TABLE IF EXISTS public.mensajeria_servicio
    ADD CONSTRAINT mensajeria_servicio_mensajero2_id_4748f870_fk_clientes_ FOREIGN KEY (mensajero2_id)
    REFERENCES public.clientes_mensajeroaquitoy (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS mensajeria_servicio_mensajero2_id_4748f870
    ON public.mensajeria_servicio(mensajero2_id);


ALTER TABLE IF EXISTS public.mensajeria_servicio
    ADD CONSTRAINT mensajeria_servicio_mensajero3_id_52b90137_fk_clientes_ FOREIGN KEY (mensajero3_id)
    REFERENCES public.clientes_mensajeroaquitoy (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS mensajeria_servicio_mensajero3_id_52b90137
    ON public.mensajeria_servicio(mensajero3_id);


ALTER TABLE IF EXISTS public.mensajeria_servicio
    ADD CONSTRAINT mensajeria_servicio_mensajero_id_db88d3fc_fk_clientes_ FOREIGN KEY (mensajero_id)
    REFERENCES public.clientes_mensajeroaquitoy (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS mensajeria_servicio_mensajero_id_db88d3fc
    ON public.mensajeria_servicio(mensajero_id);


ALTER TABLE IF EXISTS public.mensajeria_servicio
    ADD CONSTRAINT mensajeria_servicio_origen_id_2c0e307d_fk_mensajeri FOREIGN KEY (origen_id)
    REFERENCES public.mensajeria_origenservicio (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS mensajeria_servicio_origen_id_2c0e307d
    ON public.mensajeria_servicio(origen_id);


ALTER TABLE IF EXISTS public.mensajeria_servicio
    ADD CONSTRAINT mensajeria_servicio_tipo_pago_id_9a17dffb_fk_mensajeri FOREIGN KEY (tipo_pago_id)
    REFERENCES public.mensajeria_tipopago (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS mensajeria_servicio_tipo_pago_id_9a17dffb
    ON public.mensajeria_servicio(tipo_pago_id);


ALTER TABLE IF EXISTS public.mensajeria_servicio
    ADD CONSTRAINT mensajeria_servicio_tipo_servicio_id_2ecf1481_fk_mensajeri FOREIGN KEY (tipo_servicio_id)
    REFERENCES public.mensajeria_tiposervicio (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS mensajeria_servicio_tipo_servicio_id_2ecf1481
    ON public.mensajeria_servicio(tipo_servicio_id);


ALTER TABLE IF EXISTS public.mensajeria_servicio
    ADD CONSTRAINT mensajeria_servicio_tipo_vehiculo_id_97da2d5f_fk_mensajeri FOREIGN KEY (tipo_vehiculo_id)
    REFERENCES public.mensajeria_tipovehiculo (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS mensajeria_servicio_tipo_vehiculo_id_97da2d5f
    ON public.mensajeria_servicio(tipo_vehiculo_id);


ALTER TABLE IF EXISTS public.mensajeria_servicio
    ADD CONSTRAINT mensajeria_servicio_usuario_id_e8a79b11_fk_clientes_ FOREIGN KEY (usuario_id)
    REFERENCES public.clientes_usuarioaquitoy (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS mensajeria_servicio_usuario_id_e8a79b11
    ON public.mensajeria_servicio(usuario_id);


ALTER TABLE IF EXISTS public.sede
    ADD CONSTRAINT sede_ciudad_id_f2c70a92_fk_ciudad_ciudad_id FOREIGN KEY (ciudad_id)
    REFERENCES public.ciudad (ciudad_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS sede_ciudad_id_f2c70a92
    ON public.sede(ciudad_id);


ALTER TABLE IF EXISTS public.sede
    ADD CONSTRAINT sede_cliente_id_f5f1cf8b_fk_cliente_cliente_id FOREIGN KEY (cliente_id)
    REFERENCES public.cliente (cliente_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS sede_cliente_id_f5f1cf8b
    ON public.sede(cliente_id);

END;